In [ ]:
import numpy as np
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array2 = np.array([[10,11,12],[13,14,15],[16,17,18]])
array2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
array = array1+array2
print(array)
array = np.add(array1,array2)
print("\n",array)

[[11 13 15]
 [17 19 21]
 [23 25 27]]

 [[11 13 15]
 [17 19 21]
 [23 25 27]]


In [ ]:
array= array1-array2
print(array)

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [ ]:
array = array1*array2
print(array)

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [ ]:
array = array1/array2
print(array)

(array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ],
       [0.4375    , 0.47058824, 0.5       ]]), <class 'int'>)


In [ ]:
R.array = array1%array2
print(R.array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
resultarray = np.transpose(array1)
print(resultarray)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
resultarray = np.hstack((array1,array2))
print(resultarray)

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [ ]:
resultarray = np.vstack((array1,array2))
print(resultarray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
arrayrange = np.arange(0,16,1).reshape(4,4)
print(arrayrange)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
arrayrange = np.identity(3,int)
print(arrayrange)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
array1 =([1,2,3,4,5])
array2 =([6,7,8,9,10])
print(array1)
print(array2)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]


In [ ]:
print(np.add(array1,array2))
print(np.subtract(array1,array2))
print(np.multiply(array1,array2))
print(np.divide(array1,array2))

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
array1 = np.array([1,2,3,4,5,6,7,8,9])
print(np.std(array1))
print(np.min(array1))
print(np.sum(array1))
print(np.median(array1))
print(np.max(array1))
print(np.mean(array1))

2.581988897471611
1
45
5.0
9
5.0


In [ ]:
array1 = ([1,2,3])
array2 = ([4,5,6])
result1 = np.bitwise_and(array1,array2)
print(result1)
result = np.bitwise_or(array1,array2)
print(result)
result = np.left_shift(array1,2)
print(result)
result = np.right_shift(array1,2)
print(result)

[0 0 2]
[5 7 7]
[ 4  8 12]
[0 0 0]


In [ ]:
print(np.binary_repr(10,8))
result = np.left_shift(10,2)
print(result)
print(np.binary_repr(np.left_shift(10,2),8))

00001010
40
00101000


In [ ]:
array1 = np.arange(1,10)
print('array:-',array1)
new = array1.copy()
print("copy array:-",new)
array1[0] = 100
print("new array:-",array1)

array:- [1 2 3 4 5 6 7 8 9]
copy array:- [1 2 3 4 5 6 7 8 9]
new array:- [100   2   3   4   5   6   7   8   9]


In [ ]:
array1 = np.arange(1,10)
print(array1)
new = array1.view()
print(new)
array1[0] = 100
print(array1)


[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[100   2   3   4   5   6   7   8   9]


In [ ]:
array1 = np.array([[1,2,3,4,5,6],[18,14,19,20,55,60],[21,40,23,30,25,26]])
print(array1)

[[ 1  2  3  4  5  6]
 [18 14 19 20 55 60]
 [21 40 23 30 25 26]]


In [ ]:
np.sort(array1,axis=0)

array([[ 1,  2,  3,  4,  5,  6],
       [18, 14, 19, 20, 25, 26],
       [21, 40, 23, 30, 55, 60]])

In [ ]:
np.sort(array1,axis=1)

array([[ 1,  2,  3,  4,  5,  6],
       [14, 18, 19, 20, 55, 60],
       [21, 23, 25, 26, 30, 40]])

In [ ]:
array1 = np.array([1,0,3,4,0,6,7,8])
print(np.count_nonzero(array1))
print(np.nonzero(array1))
print(array1.size)

6
(array([0, 2, 3, 5, 6, 7]),)
8


In [ ]:
array1 = np.array(np.arange(1,5).reshape(2,2))
print(array1)
array2 = np.array(np.arange(11,15).reshape(2,2))
print(array2)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]


In [ ]:
new = np.stack([array1,array2],axis=0)
print(new)

[[[ 1  2]
  [ 3  4]]

 [[11 12]
  [13 14]]]


In [ ]:
new = np.stack([array1,array2],axis=1)
print(new)

[[[ 1  2]
  [11 12]]

 [[ 3  4]
  [13 14]]]


In [ ]:
array1 = np.array(np.arange(1,10).reshape(3,3))
print(array1)
array2 = np.array(np.arange(21,30).reshape(3,3))
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [ ]:
np.append(array1,array2,axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [ ]:
np.append(array1,array2,axis=1)

array([[ 1,  2,  3, 21, 22, 23],
       [ 4,  5,  6, 24, 25, 26],
       [ 7,  8,  9, 27, 28, 29]])

In [ ]:
np.concatenate((array1,array2),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [ ]:
np.concatenate((array1,array2),axis=1)

array([[ 1,  2,  3, 21, 22, 23],
       [ 4,  5,  6, 24, 25, 26],
       [ 7,  8,  9, 27, 28, 29]])

In [ ]:
array1 = np.loadtxt("/content/testmarks1.csv",delimiter=",",skiprows=1)
print(type(array1))
array1.shape

<class 'numpy.ndarray'>


(10, 5)

In [ ]:
EDS = array1[:,1]
print(EDS)

[43.05 43.47 42.24 39.24 40.9  39.47 41.68 42.19 44.75 46.95]


In [ ]:
SON = array1[:,2]
print(SON)

[27.79 28.52 28.16 26.16 26.03 26.31 25.63 27.61 28.35 28.88]
